DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

comments/urls.py
# -*- coding: utf-8 -*-  
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

mysite/urls.py
# -*- coding: utf-8 -*-  
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from blog import views
from blog.views import RSSFeed
# use Django server /media/ files

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.base, name='base'),
    url(r'^blog/$', views.home, name='home'),
    url(r'^(?P<id>\d+)/$', views.detail, name='detail'),
    url(r'^archives/$', views.archives, name = 'archives'),
    url(r'^aboutme/$', views.about_me, name = 'about_me'),
    url(r'^tag(?P<tag>\w+)/$', views.search_tag, name = 'search_tag'),
    url(r'^search/$', views.blog_search, name = 'search'),
    url(r'^source/$', views.source, name = 'source'),
    url(r'^feed/$', RSSFeed(), name = "RSS"),
    url(r'', include('comments.urls', namespace="comments")),
    url(r'^api/', include('task.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import  url
from . import views

urlpatterns = [
    url(r'^tasks/$', views.task_list, name='task_list'),    
    # url(r'^tasks/$', views.TaskList.as_view(), name='task_list'),
    # url(r'^tasks/$', views.TaskListCreate.as_view(), name='task_list'),
    url(r'^tasks/(?P<pk>[0-9]+)$', views.task_detail, name='task_detail'),
]

comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.six import python_2_unicode_compatible

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Article')

    def __str__(self):
        return self.text[:20]

comments/forms.py
# -*- coding: utf-8 -*-  
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': "名字*",
                'class':"input__field input__field--jiro",
                'type':"text",
            }),
            'email': forms.TextInput(attrs={
                'placeholder': "邮箱*",
                'class':"input__field input__field--jiro",
                'type':"email",
            }),
            'url': forms.TextInput(attrs={
                'placeholder': "网址",
                'class':"input__field input__field--jiro",
                'type':"url",
            }),
            'text': forms.Textarea(attrs={
                'placeholder': '我来评两句~',
                'class':"input-block-level comt-area",
            }),
        }

comments/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Article

from .models import Comment
from .forms import CommentForm

site = {
    'title' : u"XiChen",
    'subtitle' : 'He who thinks wins',
    
    'description' : '嗨，我是兮尘，全栈数据学徒。这里没有花俏艳丽的魔法，没有苍蛮霸道的斗气，有的，仅仅是繁衍到巅峰的代码！',
    'welcome_message' : '欢迎来到我的数据世界！',
    'blog_button':{'title':u"博客", 'description':"blog-button-description"},
    'nav' : [
        {'title':u'GitHub', 'url':'https://github.com/LinXueyuanStdio', 'description':"description", 'in_site':False},
        {'title':u'目录', 'url':'archives', 'description':"description", 'in_site':True},
        {'title':u'资源', 'url':'source', 'description':"description", 'in_site':True},
        {'title':u'RSS', 'url':'RSS', 'description':"description", 'in_site':True},
        {'title':u'关于', 'url':'about_me', 'description':"description", 'in_site':True}
    ],
    'social' : {
        'weibo':'dd',
        'github':'LinXueyuanStdio',
        'twitter':'LinXueyuanStdio',
        'zhihu':'zhihu',
        'mail':'mail',
        'copyright':'copyright'
    },
    'cover_color' : 'slate'
}

def post_comment(request, post_pk):
	# 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
	# 这里我们使用了 Django 提供的一个快捷函数 get_object_or_404，
	# 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户。
	post = get_object_or_404(Article, pk=post_pk)

	# HTTP 请求有 get 和 post 两种，一般用户通过表单提交数据都是通过 post 请求，
	# 因此只有当用户的请求为 post 时才需要处理表单数据。
	if request.method == 'POST':
		# 用户提交的数据存在 request.POST 中，这是一个类字典对象。
		# 我们利用这些数据构造了 CommentForm 的实例，这样 Django 的表单就生成了。
		form = CommentForm(request.POST)
		# 当调用 form.is_valid() 方法时，Django 自动帮我们检查表单的数据是否符合格式要求。
		if form.is_valid():
			# 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
			# commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
			comment = form.save(commit=False)

			# 将评论和被评论的文章关联起来。
			comment.post = post

			# 最终将评论数据保存进数据库，调用模型实例的 save 方法
			comment.save()
			# 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
			# 然后重定向到 get_absolute_url 方法返回的 URL。

			# 检查到数据不合法，重新渲染详情页，并且渲染表单的错误。
			# 因此我们传了三个模板变量给 detail.html，
			# 一个是文章（Post），一个是评论列表，一个是表单 form
			# 注意这里我们用到了 post.comment_set.all() 方法，
			# 这个用法有点类似于 Post.objects.all()
			# 其作用是获取这篇 post 下的的全部评论，
			# 因为 Post 和 Comment 是 ForeignKey 关联的，
			# 因此使用 post.comment_set.all() 反向查询全部评论。
			# 具体请看下面的讲解。
			try:
				page = {'layout':'post'}
				tags = post.tag.all()
				# 记得在顶部导入 CommentForm
				form = CommentForm()
				# 获取这篇 post 下的全部评论
				comment_list = post.comment_set.all()
				# 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
				context = {'post':post, 'tags':tags, 
		                    'site':site, 'page':page,
		                    'form':form, 'comment_list':comment_list}
			except Article.DoesNotExist:
				raise Http404
			return render(request, 'post.html', context)
	# 不是 post 请求，说明用户没有提交数据，重定向到文章详情页。
	return redirect(post)

templates/aboutme.html
{% extends "base.html" %}
{% load custom_markdown %}

{% block content %}
<div class="posts">
    <ol class="time-line">
        {% for post in post_list %}
            <li>
                <p class="post-meta">
                    <a class="post-list__meta--date date" href="{{ post.raw_url }}">{{ post.date_time |date:'Y M d H:i a'}}</a>
                    &#8226; 
                      <a class="post-category post-category-pure" href="{{ post.raw_url }}" style="display:inline-block;">{{ post.things }}</a>
                </p>
            </li>
        {% endfor %}
    </ol>
</div><!-- /.blog-post -->
{% endblock %}     

templates/archives.html
{% extends "base.html" %}

{% block content %}
<div class="posts">
    <form class="pure-form pure-menu-horizontal" action="/search/" method="get">
        <input class="pure-input-2-2" style="width:100%;" type="text" name="s" placeholder="search">
    </form>
    <section class="post-hr">
        <hr>
    </section>

    {% if error %}
        <h2 class="post-title">没有相关文章题目</h2>
    {% else %}
        <ol class="time-line">
            {% for post in post_list %}
                <li>
                    <h1 class="time-line-title">
                        <a href="{% url 'detail' id=post.id %}">
                            {{ post.title }}
                        </a>
                    </h1>

                    <p class="post-meta">
                        <a class="post-list__meta--date date" href="#">{{ post.date_time |date:'Y M d'}}</a>
                        &#8226; 
                        {% for tag in post.tag.all %}
                          <a class="post-category post-category-pure" href="{% url 'search_tag' tag=tag %}">{{ tag.tag_name }}</a>
                        {% endfor %}
                    </p>
                </li>
            {% endfor %}
        </ol>
    {% endif %}
    {% include "side-bar.html" %}
</div><!-- /.blog-post -->
{% endblock %}      

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body>

    <span class="mobile btn-mobile-menu">
        <i class="fa fa-list btn-mobile-menu__icon"></i>
        <i class="fa fa-angle-up btn-mobile-close__icon hidden"></i>
    </span>
    
    {% include 'side-panel.html' %}

    <div class="content-wrapper">
        <div class="content-wrapper__inner">
            {% block content %}
            {% endblock %}
            {% include 'footer.html' %}
        </div>
    </div>

{% include 'externals.html' %}

</body>
</html>

templates/comment.html
<section class="comment-area">
    <section class="post-hr">
        <hr>
    </section>
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <span class="input input--jiro">
                {{ form.name }}
                {{ form.name.errors }}
                <label class="input__label input__label--jiro" for="{{ form.name.id_for_label }}">
                    <span class="input__label-content input__label-content--jiro">Name</span>
                </label>
            </span>

            <span class="input input--jiro">
                {{ form.email }}
                {{ form.email.errors }}
                <label class="input__label input__label--jiro" for="{{ form.email.id_for_label }}">
                    <span class="input__label-content input__label-content--jiro">Email</span>
                </label>
            </span>

            <span class="input input--jiro">
                {{ form.url }}
                {{ form.url.errors }}
                <label class="input__label input__label--jiro" for="{{ form.url.id_for_label }}">
                    <span class="input__label-content input__label-content--jiro">Url</span>
                </label>
            </span>

            <span class="input-block-level">
                {{ form.text }}
                {{ form.text.errors }}
            </span>

            <button type="submit" class="btn btn-primary comment-submit"><span>发表</span></button>

        </div>    <!-- row -->
    </form>
    <hr>
    <div class="comment-list">
        <ul class="list-unstyled">
            {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="name">{{ comment.name }}</span>
                    <time class="date">{{ comment.created_time }}</time>
                    <div class="text" style="font-size:14px;padding-left:28px">
                        {{ comment.text }}
                    </div>
                </li>
            {% empty %}
              <section class="post-hr">
                <hr>
              </section>
            {% endfor %}
        </ul>
    </div>
</section>

templates/externals.html
<script type="text/javascript" src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<!--使markdown支持latex-->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
        inlineMath: [ ['$', '$'] ],
        displayMath: [ ['$$', '$$']],
        processEscapes: true,
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
    },
    messageStyle: "none",
    "HTML-CSS": { preferredFont: "TeX", availableFonts: ["STIX","TeX"] }
});
</script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=default"></script>
<!--载入本地js文件-->
{% load staticfiles %}
<script type="text/javascript" src="{% static "js/highlight.pack.js" %}"></script>
<script>hljs.initHighlightingOnLoad();</script>

<script type="text/javascript" src="{% static "js/main.js" %}"></script>
<script type="text/javascript" src="{% static "js/widget-move.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery.poshytip.min.js" %}"></script>

templates/footer.html
<section class="footer">
<div class="footer">
    <footer >
        <ul class="pure-menu pure-menu-horizontal pure-menu-open">
            <li><a href="#">About Me</a></li>
            <li><a href="http://twitter.com/Dlinking">Twitter</a></li>
            <li><a href="http://github.com/LinXueyuanStdio">GitHub</a></li>
        </ul>
        <span class="footer__copyright">本站点采用 <a rel="license" href="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh">知识共享 署名-非商业性使用-禁止演绎 4.0 国际 许可协议</a></span>
    </footer>
</div>
</section>

templates/head.html
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="theme-color" content="#343434">

  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A layout example that shows off a blog page with a list of posts.">

  <title>{% block title %} DLinking Blog {% endblock %}</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
  <link rel="stylesheet" href="http://picturebag.qiniudn.com/monokai.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.gdgdocs.org/css?family=Lobster" rel="stylesheet" type="text/css">
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <link rel="stylesheet" href="{% static "css/tip-twitter/tip-twitter.css" %}">
  <!--阅读次数统计-->
  <script async src="https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"> </script>
</head>

templates/home.html
{% extends "base.html" %}

{% load custom_markdown %}
{% block content %}
<div class="posts">
  <form class="pure-form pure-menu-horizontal" action="/search/" method="get">
    <input class="pure-input-2-2" style="width:100%;" type="text" name="s" placeholder="search">
  </form>
  <section class="post-hr">
    <hr>
  </section>
  <article class="post-container post-container--single" itemscope itemtype="http://schema.org/BlogPosting">
    
    {% for post in post_list %}
    <section class="post">
      <header class="post-header">
        <h2 class="post-title">
          <a href="{% url 'detail' id=post.id %}" title="{{ post.title }}">{{ post.title }}</a>
        </h2>
      </header>

      <div class="excerpt post-description post-content">
        <p>
          {{ post.content|custom_markdown| truncatechars_html:200 }}
        </p>
      </div>

      <p class="post-readmore ">
        <a class="btn-border-small" href="{% url 'detail' id=post.id %}">Read More >>></a>
        &emsp;&emsp;<i class="fa fa-calendar"></i>
        <a class="post-list__meta--date date" href="#">{{ post.date_time |date:'Y M d'}}</a>
         &#8226; 
        {% for tag in post.tag.all %}
          <a class="post-category post-category-pure" href="{% url 'search_tag' tag=tag %}">{{ tag.tag_name }}</a>
        {% endfor %}
      </p>
    </section>
    {% endfor %}
  </article>
  {% include 'readmore.html' %}
  {% include 'side-bar.html' %}
</div><!-- /.blog-post -->

{% endblock %}      

templates/index.html
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

templates/side-panel.html
{% load staticfiles %}
<header class="panel-cover  {% if page.layout == 'post' or page.layout == 'page' %}panel-cover--collapsed{% else %}isHidden{% endif %}" style="background-image: url('{% static "images/background-cover.jpg" %}')">
  <div class="panel-main">

    <div class="panel-main__inner panel-inverted">
      <div class="panel-main__content">
        <!--头像-->
        <a href="{% url 'base' %}" title="前往 {{ site.title }} 的主页" class="blog-button logo-a">
          <img src="{% static "images/avatar.jpg" %}" width="80" alt="{{ site.title }} logo" class="panel-cover__logo logo" />
        </a>
        <!--昵称-->
        <h1 class="panel-cover__title panel-title" style="font-family: Lobster, Monospace;">
          <a href="{% url 'base' %}" title="link to homepage for {{ site.title }}" class="blog-button">
            {{ site.title }}
          </a>
        </h1>
        <!--格言-->
        {% if site.subtitle %}
          <span class="panel-cover__subtitle panel-subtitle">
            {{site.subtitle}}
          </span>
        {% endif %}
        <!--个人简介-->
        <hr class="panel-cover__divider" />
        <p  class="panel-cover__description">{{ site.description }}</p>
        <hr class="panel-cover__divider panel-cover__divider--secondary" />
        <!--欢迎-->
        {% if site.welcome_message %}
        <p class="panel-cover__description">{{ site.welcome_message }}</p>
        {% endif %}
        <!--链接-->
        <div class="navigation-wrapper">
          <!--内链-->
          <div>
            <nav class="cover-navigation cover-navigation--primary">
              <ul class="navigation">
                <li class="navigation__item">
                  <a href="{% url 'home' %}" title="{{site.blog_button.description}}" class="blog-button">
                    {{site.blog_button.title}}
                  </a>
                </li>
                {% for item in site.nav %}
                  {% if item.in_site %}
                    <li class="navigation__item">
                      <a href="{% url item.url %}" title="{{item.description}}">
                      {{item.title}}
                      </a>
                    </li>
                  {% else %}
                    <li class="navigation__item">
                      <a href="{{item.url}}" target="_blank" title="{{item.description}}">
                        {{item.title}}
                      </a>
                    </li>
                  {% endif %}
                {% endfor %}
              </ul>
            </nav>
          </div>
          
          <!--外链-->
          <div>{% include 'social.html' %}</div>
        </div>
      </div>
    </div>
    
    {% if site.cover_color %}
    <div class="panel-cover--overlay cover-{{site.cover_color}}"></div>
    {% else %}
    <div class="panel-cover--overlay cover-disabled"></div>
    {% endif %}
  </div>
  {% include 'side-icons.html' %}
  {% include 'to-top.html' %}
</header>

templates/social.html
<nav class="cover-navigation navigation--social">
  <ul class="navigation">

  {% if site.social.weibo %}
  <!-- Weibo -->
  <li class="navigation__item">
    <a href="http://weibo.com/{{site.social.weibo}}" title="@{{site.social.weibo}} 的微博" target="_blank">
      <i class='social fa fa-weibo'></i>
      <span class="label">Weibo</span>
    </a>
  </li>
  {% endif %}

  {% if site.social.github %}
  <!-- Github -->
  <li class="navigation__item">
    <a href="https://github.com/{{site.social.github}}" title="@{{site.social.github}} 的 Github" target="_blank">
      <i class='social fa fa-github'></i>
      <span class="label">Github</span>
    </a>
  </li>
  {% endif %}
  
  {% if site.social.twitter %}
  <!-- Twitter -->
  <li class="navigation__item">
    <a href="http://twitter.com/{{site.social.twitter}}" title="@{{site.social.twitter}}" target="_blank">
      <i class='social fa fa-twitter'></i>
      <span class="label">Twitter</span>
    </a>
  </li>
  {% endif %}

    {% if site.social.zhihu %}
  <!-- Zhihu -->
  <li class="navigation__item">
    <a href="https://www.zhihu.com/people/{{site.social.twitter}}" title="@{{site.social.twitter}}" target="_blank">
      <i class='social fa fa-graduation-cap'></i>
      <span class="label">知乎</span>
    </a>
  </li>
  {% endif %}

  {% if site.social.gplus %}
  <!-- Google Plus -->
  <li class="navigation__item">
    <a href="https://plus.google.com/{{site.social.gplus}}" rel="author" title="Google+" target="_blank">
      <i class='social fa fa-google-plus-square'></i>
      <span class="label">Google Plus</span>
    </a>
  </li>
  {% endif %}

  {% if site.social.rss %}
  <!-- RSS -->
  <li class="navigation__item">
    <a href="/feed.xml" rel="author" title="RSS" target="_blank">
      <i class='social fa fa-rss'></i>
      <span class="label">RSS</span>
    </a>
  </li>
  {% endif %}

  {% if site.social.mail %}
  <!-- Email -->
  <li class="navigation__item">
    <a href="mailto:{{site.social.mail}}" title="发邮件给我">
      <i class='social fa fa-envelope'></i>
      <span class="label">Email</span>
    </a>
  </li>
  {% endif %}

  {% if site.social.copyright %}
  <!-- Copyright -->
  <li class="navigation__item">
    <a href="{{site.social.copyright}}" title="选择版权"  target="_blank">
      <i class="social fa fa-copyright"></i>
      <span class="label">版权</span>
    </a>
  </li>
  {% endif %}
  
  </ul>
</nav>









<!--

<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">

            <div class="header">
            <h1 class="brand-title"><a href="{% url 'home' %}">Dlinking Blog</a></h1>
            <h2 class="brand-tagline">兮尘 - Xi Chen</h2>
            <nav class="nav">
                <ul class="nav-list">
                    <li>
                        <form class="pure-form" action="/search/" method="get">
                        <input class="pure-input-3-3" type="text" name="s" placeholder="search">
                        </form>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button" href="/">主页</a>
                    </li>


                    <li class="nav-item">
                        <a class="button-success pure-button" href="{% url 'archives' %}">归档</a>
                    </li>

                    
                    <li class="nav-item">
                        <a class="button-success pure-button" href="/">专题</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="https://github.com/LinXueyuanStdio">Github</a>
                    </li>


                    <li class="nav-item">
                        <a class="button-success pure-button" href="{% url 'about_me' %}">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button" href="{% url 'RSS' %}">RSS</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>

        </div>
    </div>
</div>

-->

templates/source.html
{% extends "base.html" %}

{% block content %}
<div class="posts">
    
    {% for post_class in post_class_list %}
        <div class="row" style="text-align:center">  
            <h3>{{post_class.src_class}}</h3>
            <p><small>{{post_class.intro}}</small></p>
        </div>
        
        <div class="row-border" style="text-align:center;"> 
            <ol class="list-inline">
            
            {% for post in post_list %}
{% ifequal post_class.src_class post.src_class.src_class %}
            
                <li>
                    <a class="btn-border-small btn-default" target="_blank" href="{{ post.src_url }}" role="button" title="{{ post.src_hint }}">
                        {{ post.src_title }}
                        {% if post.src_marks %}
                        <a class="post-category post-category-pure badge try8-remark">
                            {{ post.src_marks }}
                        </a>
                        {% endif %}
                    </a>
                </li>
{% endifequal %}
            {% endfor %}
            </ol>
        </div>
        <div style="margin-bottom: 80px"></div>
    {% endfor %}
{% include 'side-bar.html' %}
</div><!-- /.blog-post -->

{% endblock %}    

<div class="marketing">
  
  <div class="row-border" style="text-align:center;">  
    <div id="site-1" >
      <ul class="list-inline">
        <li><a class="btn btn-default" target="_blank" href="https://www.w3.org/" role="button" title=" 英文网址： https://www.w3.org/">W3C<span class="badge try8-remark">官方网站</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="http://www.runoob.com/" role="button" title="中文网址：http://www.runoob.com/">菜鸟教程<span class="badge try8-remark">在线文档</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="http://www.bootcss.com/" role="button" title="中文网址：http://www.bootcss.com/">Bootstrap<span class="badge try8-remark">前端框架</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="http://www.qdfuns.com/" role="button" title="中文网址：http://www.qdfuns.com/">前端网<span class="badge try8-remark">综合社区</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="https://jquery.com/" role="button" title=" 英文网址： https://jquery.com/">jQuery<span class="badge try8-remark">JS框架</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="http://960.gs/" role="button" title=" 英文网址： http://960.gs/">960 Grid System<span class="badge try8-remark">CSS框架</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="http://www.cssmoban.com/" role="button" title="中文网址：http://www.cssmoban.com/">模板之家<span class="badge try8-remark">模板下载</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="http://fontawesome.io/" role="button" title=" 英文网址： http://fontawesome.io/">Font Awesome<span class="badge try8-remark">图片图标</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="http://mobilehtml5.org/" role="button" title=" 英文网址： http://mobilehtml5.org/">HTML5 compatibility<span class="badge try8-remark">兼容测试</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="https://dribbble.com/" role="button" title=" 英文网址： https://dribbble.com/">Dribbble<span class="badge try8-remark">UI设计</span></a></li>
        <li><a class="btn btn-default" target="_blank" href="http://www.sublimetext.com/" role="button" title=" 英文网址： http://www.sublimetext.com/">Sublime Text<span class="badge try8-remark">开发工具</span></a></li>
    
      </ul>
    </div>
  </div>  
</div>